import { getGoogleGenAIClient } from "@/lib/google/genai-client";
import type { ScoutBriefTranscript, ScoutBriefSpeaker } from "@/features/scout-brief/types";
import { extractPcmFromWav, concatAudioSegments, generateSyntheticPcm } from "./audio-processor";

export interface TtsGenerationOptions {
  modelId?: string;
  speakers?: [ScoutBriefSpeaker, ScoutBriefSpeaker];
  apiKey?: string;
}

export interface TtsGenerationResult {
  base64Pcm: string;
  durationSeconds: number;
  sampleRate: number;
}

/**
 * Pronunciation map for proper nouns and creator names.
 */
export const PRONUNCIATION_DICTIONARY: Record<string, string> = {
  "Junichiro": "Joon-ee-chee-roh",
  "Vampair": "Vamp-air",
  "TeamTO": "Team-T-O",
  "Chaz Bottoms": "Chazz Bottoms",
};

/**
 * Formats the transcript into the canonical multi-speaker dialogue text for Gemini TTS.
 */
export function formatDialoguePrompt(transcript: ScoutBriefTranscript): string {
  const lines: string[] = [
    "Read the following two-speaker executive audio briefing with professional clarity and natural conversational pacing.",
    "Keep Scout engaged, enthusiastic, and curious. Keep Analyst measured, precise, and analytical.",
    "",
  ];

  transcript.segments.forEach((seg) => {
    lines.push(`${seg.speaker}: ${seg.text}`);
  });

  return lines.join("\n\n");
}

/**
 * Generates multi-speaker real voice audio from a structured Scout Brief transcript using Google GenAI.
 * Uses 'Kore' for Scout and 'Puck' for Analyst.
 * Combines multi-turn PCM streams into a single seamless audio track.
 * Fails truthfully when credentials are missing or generation fails.
 */
export async function generateMultiSpeakerAudio(
  transcript: ScoutBriefTranscript,
  options: TtsGenerationOptions = {}
): Promise<TtsGenerationResult> {
  const isTest = process.env.NODE_ENV === "test" || Boolean(process.env.VITEST);
  const ai = getGoogleGenAIClient();
  const modelId = options.modelId || process.env.GEMINI_TTS_MODEL_ID || "gemini-2.5-flash-preview-tts";

  const speakerVoices: Record<string, string> = {
    Scout: options.speakers?.[0]?.voice || "Kore",
    Analyst: options.speakers?.[1]?.voice || "Puck",
  };

  // If live GenAI client is available and not in test mode, generate real Google speech
  if (ai && !isTest) {
    try {
      const pcmBuffers: Buffer[] = [];
      const sampleRate = 24000;

      for (const segment of transcript.segments) {
        const voiceName = speakerVoices[segment.speaker] || "Puck";
        const prompt = segment.text;

        const response = await ai.models.generateContent({
          model: modelId,
          contents: prompt,
          config: {
            responseModalities: ["AUDIO"],
            speechConfig: {
              voiceConfig: {
                prebuiltVoiceConfig: {
                  voiceName,
                },
              },
            },
          },
        });

        const part = response.candidates?.[0]?.content?.parts?.[0];
        if (part && part.inlineData && part.inlineData.data) {
          const rawBuf = Buffer.from(part.inlineData.data, "base64");
          // Extract PCM if the model returns a containerized WAV, else use raw bytes
          const pcmBuf = rawBuf.subarray(0, 4).toString("ascii") === "RIFF"
            ? extractPcmFromWav(rawBuf)
            : rawBuf;
          pcmBuffers.push(pcmBuf);
        } else {
          throw new Error(`[ScoutBrief] Gemini TTS returned no audio data for segment ${segment.order}`);
        }
      }

      if (pcmBuffers.length === 0) {
        throw new Error("[ScoutBrief] No audio segments generated by Gemini TTS");
      }

      const unifiedAudio = concatAudioSegments(pcmBuffers);
      const durationSeconds = Math.max(1, Math.round(unifiedAudio.durationMs / 1000));
      const rawPcm = extractPcmFromWav(unifiedAudio.wavBuffer);

      return {
        base64Pcm: rawPcm.toString("base64"),
        durationSeconds,
        sampleRate,
      };
    } catch (err) {
      console.error("[ScoutBrief] Gemini TTS generation failed:", err);
      throw new Error(`[ScoutBrief] Gemini speech generation failed: ${err instanceof Error ? err.message : String(err)}`);
    }
  }

  // In test environment, return deterministic PCM for unit tests
  if (isTest) {
    const wordCount = (transcript?.segments || []).reduce(
      (acc, seg) => acc + (seg.text || "").trim().split(/\s+/).filter(Boolean).length,
      0
    );
    const durationSeconds = Math.max(30, Math.min(300, Math.round((wordCount / 140) * 60)));
    const base64Pcm = generateSyntheticPcm(durationSeconds, 24000, 440);

    return {
      base64Pcm,
      durationSeconds,
      sampleRate: 24000,
    };
  }

  // Production without credentials: fail truthfully
  throw new Error("[ScoutBrief] Gemini TTS speech generation unavailable: missing credentials or provider call failed. Synthetic tone fallbacks are disabled in production.");
}
